spring.application.name=appliance-assistant
server.port=9090
# PostgreSql settings
spring.datasource.url=jdbc:postgresql://localhost:5432/postgres
spring.datasource.username=postgres
spring.datasource.password=123
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect
# AI settings
spring.ai.anthropic.api-key=${ANTHROPIC_API_KEY:default}
spring.ai.anthropic.chat.options.model=claude-haiku-4-5-20251001
spring.ai.anthropic.base-url=https://api.anthropic.com
spring.ai.anthropic.chat.options.max-tokens=2000
spring.ai.chat.client.enabled=true
